version: "3.7"

services:
  govidia_web:
    image: amon/govidia_web:latest
<<<<<<< HEAD
    environment:
      - NODE_ENV=production
#    ports: 
#        - 3000:3000
    network_mode: "host"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000 || exit 1
      interval: 600s
      retries: 5
      start_period: 5s
      timeout: 10s
=======
    # ports:
    #   - 8081:5000
    network_mode: "host"
>>>>>>> d516617adff6cc8b8f0cafc49952fc4fa858c5a9
